pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build') {
      steps {
        sh 'docker compose build'
      }
    }

    stage('Test') {
      steps {
        sh 'docker compose up -d'
        sh 'docker compose exec -T web pytest --cov=.'
      }
    }
  }

  post {
    always {
      sh 'docker compose logs --no-color'
      sh 'docker compose down -v'
    }
  }
}
