# Generated by Django 5.1.4 on 2026-01-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('village', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_per_share', models.PositiveBigIntegerField(default=0)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
