# Generated by Django 5.1.4 on 2026-01-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coops/'),
        ),
    ]
