# Generated by Django 5.1.4 on 2026-01-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coops', '0002_cooperative_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='available_primary_shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
